language: objective-c
cache: cocoapods
podfile: Example/Podfile
install:
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
before_script:
- cd Example && pod install && cd -
script:
- set -o pipefail && xcodebuild build -workspace Example/WPMediaPicker.xcworkspace -scheme WPMediaPicker-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
