version: 2.1

orbs:
  # This uses the iOS Orb located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@0.0.25

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Test
          xcode-version: "11.0"
          carthage-update: true
          carthage-working-directory: Example
          bundle-install: false
          pod-install: false
          workspace: Aztec.xcworkspace
          scheme: AztecExample
          device: iPhone 11
          ios-version: "13.0"

      - ios/validate-podspec:
          name: Validate WordPress-Aztec-iOS.podspec
          xcode-version: "11.0"
          podspec-path: WordPress-Aztec-iOS.podspec

      - ios/validate-podspec:
          name: Validate WordPress-Editor-iOS.podspec
          xcode-version: "11.0"
          podspec-path: WordPress-Editor-iOS.podspec
          # Updating specs is needed since WordPress-Editor-iOS depends on WordPress-Aztec-iOS
          update-specs-repo: true
